### ISSUE TITLE
Some translation(ES) not ship on the last version

### ISSUE THREAD

**Issue by Caballlero** [GoAlexander/harbour-editor#100]

**Comment by GoAlexander** [comment]
I know... Unfortunately last time I have busy with another tasks or lazy :(((  
I will try to do something in next week but can not promise...

**Comment by GoAlexander** [comment]
Finally I pushed new translations. Hope it will be fixes when I release new version,

**Comment by Caballlero** [comment]
Thanks Alexander , Give me 24 hours to translate new strings.
Any news on save in cloud(openbox) ?

**Comment by GoAlexander** [comment]
Ok, the update will be not soon because I want to implement these (or most of these):
- https://trello.com/c/glEj94kD/152-fix-historypage-delete-removes-all-history
- https://trello.com/c/I8Msi0RL/153-save-as-reopen-file-only-if-saving-was-successful
- https://trello.com/c/InB5XD5c/157-reopen-last-closed-file-optional-in-settings
- https://trello.com/c/9XtE9vgi/154-zim-mode
  
Cloud is very far in my todo list :)  
Last time I use Editor for editing my To Do list in zim format + syncthing for the synchronization with my desktop.

**Comment by GoAlexander** [comment]
@Caballlero I implemented not all what wanted but I published new update in all stores (openrepos and harbour (in QA))

**Comment by Caballlero** [comment]
yes everything ok. But please  zim-mode is wanted :  )

**Comment by GoAlexander** [comment]
In this case I close this issue.
It is very hot time for me now because I have to finish and present my diploma in one month. So I am not sure when I will publish new version.

As first feature of zim-mode I want to do this:
"Add buttons [ ], [*], [x]. These buttons replace (or simple add) existing [] in current row with [] from button"
Because I use zim as To Do list in my phone.
Note that it will be not re-rendered (as in desktop app) so it will be plain text.
If you want to have some features for zim which are easy to implement you can create new issue - I will try to do it. :)
