### ISSUE TITLE
[Bug] Saving empty files with Editor.

### ISSUE THREAD

**Issue by Olf0** [GoAlexander/harbour-editor#75]
Ugly bug, saving empty files with Editor. 0.7.1 under SailfishOS 2.1.0.11:

1. Open Editor. 
2. Type text. 
3. Hit "Save": "Document can't be saved!" 
4. Thinking, "Oh, I forgot to set a file path".
5. Hit "Save as" (then choose a file and save): A 0 byte file is saved! 
6. Typed text is gone!

Expected behaviour: 
- "Save" calls "Save as", when no file path has been chosen before (as other editors do). 
- Error message is still valid (and needed) for e.g. read-only files.  "Failed to write file!" or "Failed to save document!" might be more concise, though. 
- Document must not be emptied, when an unsuccessful "Save" (e.g. to a read-only file) is followed by a "Save as" (the logical users' reaction)! 

BTW (minor usability nuisance), Editor. does not display its version number in Settings --> About 

HTH & kudos for your excellent Editor.

**Comment by GoAlexander** [comment]
Oh... It is because of code for highlighting... I think I know where is this bug. I am very busy at the university now but I will try to publish fix soon as possible.

Thanks for the feedback.

**Comment by GoAlexander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Пофиксить: https://github.com/GoAlexander/harbour-editor/issues/75](https://trello.com/c/vVDQMCqO/109-https-github-com-goalexander-harbour-editor-issues-75)

**Comment by GoAlexander** [comment]
Bug fixed in version 0.7.3.  

If you will find some more bugs write me. Sometimes I does not have enough time for testing of all possible situations.

**Comment by GoAlexander** [comment]
> Document must not be emptied, when an unsuccessful "Save" (e.g. to a read-only file) is followed by a "Save as" (the logical users' reaction)!
Is it emptied when you open read only file and press `Save`?!

**Comment by GoAlexander** [comment]
If you have any suggestions please write them as `issues`. That will be much easier to operate with them for me.

**Comment by GoAlexander** [comment]
f77a9d4cead8f0fa826c55a1529489cf4315b4c6

**Comment by Olf0** [comment]
@GoAlexander, wow, that was quick: Thank you. 

a. 
> If you will find some more bugs write me. 
If I do, I would open an issue here.  Is that what you meant with, "... write me."? 

b. 
> Is it emptied when you open read only file and press Save?! 
Will do a final test of issue #75 (if being resolved now), when I receive this update via Jolla Store. 

c. 
> If you have any suggestions please write them as issues. 
Mmmh, I do not fully comprehend this statement, as I wrote this as an issue.  Do you mean, I shall tag such issues opened here as "Bug"? 
To be honest, I realised that you keep things very organised by using these utilities at Github extensively (and by using Trello), but when I created this issue here, I did not find the "Set label"-function right away.  I never used labels on issues at Github before, as most other software authors do not use them, but will search a bit more thoroughly the next time. 

Side note: Glad to see that you prioritise your studies at university over coding.  Seriously, as much as I love the results of your work, I know (out of experience) that you and your work will have much more impact with a university degree and working in a position for an academic later.  

Cheers & all the best.

**Comment by GoAlexander** [comment]
> If I do, I would open an issue here. Is that what you meant with, "... write me."?

Yes, you are right :)

>Will do a final test of issue #75 (if being resolved now), when I receive this update via Jolla Store.

Ok. Version 0.7.3 is already ready for install in openrepos and in QA (waiting confirmation of Jolla) in harbour.
As bonus you will find some additional features you can see changelog here: https://github.com/GoAlexander/harbour-editor/issues/19#issuecomment-303670317
:)
  

> Mmmh, I do not fully comprehend this statement, as I wrote this as an issue. Do you mean, I shall tag such issues opened here as "Bug"?
To be honest, I realised that you keep things very organised by using these utilities at Github extensively (and by using Trello), but when I created this issue here, I did not find the "Set label"-function right away. I never used labels on issues at Github before, as most other software authors do not use them, but will search a bit more thoroughly the next time.

Relax :)  I don` t demand to fully formalize issues I only request users to write information about bugs/suggestions in github to save (a bit) my time and not to forget about them. So simple issue with description of bug or suggestion is enough.

> Side note: Glad to see that you prioritise your studies at university over coding. Seriously, as much as I love the results of your work, I know (out of experience) that you and your work will have much more impact with a university degree and working in a position for an academic later.

Thank you that you understand it. I develop this app not for money so this kind of words makes me pleased motivates :)))
Note: I got the position in company where I wanted (long time). So I think I will make updates not so active for the next some months because I have exams and I have to adopt to work in the company :)))
  
If you have **any** questions about the app (how to use, plans etc) you can write me via email or telegram.

**Comment by Olf0** [comment]
This issue is fixed.

But obviously there was not much testing of Editor.'s handling of read-only files.  Done, see issue .

**Comment by GoAlexander** [comment]
Ok. Open the issue I will read it :)
